version: "3"

services:
    gui:
        image: gui
        volumes:
            - ./gui/src:/app/src
        ports:
            - "3000:3000"
        networks:
            - basic_net
        environment:
            - WATCHPACK_POLLING=true
    webservice:
        image: webservice
        ports:
            - "8000:8000"
        environment:
            - ECU_IP=10.0.2.1
            - ECU_PORT=10001
            - GSE_IP=10.0.2.0
            - GSE_PORT=10001
        volumes:
            - ./webservice:/app
        healthcheck:
            test: curl --fail http://localhost:8000/ecu/state || exit 1
            interval: 20s
        networks:
            - basic_net
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: rocket2
            POSTGRES_USER: gs
            POSTGRES_PASSWORD: rocket
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        networks:
            - basic_net
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
networks:
    basic_net:
        driver: bridge
