version: "3"

services:
    frontend:
        image: frontend
        volumes:
            - ./frontend/src:/app/src
        ports:
            - "3000:3000"
        networks:
            - basic_net
        environment:
            - WATCHPACK_POLLING=true
    webservice:
        image: webservice
        ports:
            - "8000:8000"
        volumes:
            - ./webservice:/app
        networks:
            - basic_net
        healthcheck:
          test: curl --fail http://localhost:8000/ecu/state || exit 1
          interval: 20s

    postgres:
        image: postgres
        restart: always
        environment:
            POSTRGRES_DB: rocket2
            POSTGRES_USER: gs
            POSTGRES_PASSWORD: rocket
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        networks:
            - basic_net
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
networks:
    basic_net:
        driver: bridge
