import {createAsyncThunk, createSlice} from "@reduxjs/toolkit";
import {getRocketState, updateRocket} from "../webservice";

const initialState = {
    solenoids: {},
    pts: {},
    tcs: {}
};

export const fetchRocketState = createAsyncThunk("rocket/fetchRocketState", async (_, {dispatch}) => {
    try {
        const rocketState = (await getRocketState()).data;
        console.log("recv", rocketState);

        let solenoids = {};
        let pts = {};
        let tcs = {};

        for (const key in rocketState) {
            if (key.includes("solenoid")) {
                let solenoidType =  key.includes("Expected") ? "expected": "current";
                let solenoidName = key.includes("Expected") ? key.split("Expected")[1] : key.split("Current")[1] ;
                if (!Object.keys(solenoids).includes(solenoidName)) {
                    solenoids[solenoidName] = { "expected": 0,
                "current":0};
                }
                solenoids[solenoidName][solenoidType] = rocketState[key];
            }

            if (key.includes("temperature")) {
                let key_name = key.substring(11, key.length);
                tcs[key_name] = rocketState[key];
            }

            if (key.includes("pressure")) {
                let key_name = key.substring(8, key.length);
                pts[key_name] = rocketState[key];
            }
        }
        console.log("solenoids", solenoids);
        dispatch(setPts(pts));
        dispatch(setSolenoids(solenoids));
        dispatch(setTcs(tcs))

    } catch (error) {
        // Handle errors (dispatch an error action or throw the error)
        throw error;
    }
});

export const setRocketSolenoid = createAsyncThunk("rocket/setRocketSolenoid", async ({solenoidName, solenoidState}, {dispatch}) => {
    try {
        const response = await updateRocket(solenoidName, solenoidState);
    } catch (error) {
        // Handle errors (dispatch an error action or throw the error)
        throw error;
    }
});

export const rocketSlice = createSlice({
    name: "rocket",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        toggleSolenoid: (state, action) => {
            const solenoidName = action.payload;
            state.solenoids[solenoidName]["expected"] = !state.solenoids[solenoidName]["expected"];
            console.log("state updated");
        },
        setSolenoids: (state, action) => {
            for (let solenoidName in action.payload) {
                state.solenoids[solenoidName] = action.payload[solenoidName];
            }
        },
        setPts: (state, action) => {
            for (let ptName in action.payload) {
                state.pts[ptName] = action.payload[ptName];
            }
        },
        setTcs: (state, action) => {
            for (let tcName in action.payload) {
                state.tcs[tcName] = action.payload[tcName];
            }
        }
    }
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    // extraReducers: (builder) => {
    //   builder
    //     .addCase(incrementAsync.pending, (state) => {
    //       state.status = 'loading';
    //     })
    //     .addCase(incrementAsync.fulfilled, (state, action) => {
    //       state.status = 'idle';
    //       state.value += action.payload;
    //     });
    // },
});

export const {toggleSolenoid, setSolenoids, setPts, setTcs} = rocketSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

export const selectSolenoids = (state) => state.rocket.solenoids;
export const selectPts = (state) => state.rocket.pts;
export const selectTcs = (state) => state.rocket.tcs;


export default rocketSlice.reducer;

// expected, current
// solenoidFeedbackName
// solenoidExpectedName
// key.split