GSE_DATA_FORMAT = [
    "time_recv",
    "igniterArmed",
    "igniter0Continuity",
    "igniter1Continuity",
    "igniterInternalState0",
    "igniterInternalState1",
    "alarmInternalState",
    "solenoidInternalStateGn2Fill",
    "solenoidInternalStateGn2Vent",
    "solenoidInternalStateMvasFill",
    "solenoidInternalStateMvasVent",
    "solenoidInternalStateMvas",
    "solenoidInternalStateLoxFill",
    "solenoidInternalStateLoxVent",
    "solenoidInternalStateLngFill",
    "solenoidInternalStateLngVent",
    "supplyVoltage0",
    "supplyVoltage1",
    "solenoidCurrentGn2Fill",
    "solenoidCurrentGn2Vent",
    "solenoidCurrentMvasFill",
    "solenoidCurrentMvasVent",
    "solenoidCurrentMvas",
    "solenoidCurrentLoxFill",
    "solenoidCurrentLoxVent",
    "solenoidCurrentLngFill",
    "solenoidCurrentLngVent",
    "temperatureLox",
    "temperatureLng",
    "pressureGn2"
    ]

GSE_COMMAND_FORMAT =[
    ("igniterInternalState0", "igniter0Continuity"),
    ("igniterInternalState1", "igniter1Continuity"),
    ("alarmInternalState", "alarmInternalState"),
    ("solenoidInternalStateGn2Fill","solenoidCurrentGn2Fill"),
    ("solenoidInternalStateGn2Vent","solenoidCurrentGn2Vent"),
    ("solenoidInternalStateMvasFill","solenoidCurrentMvasFill"),
    ("solenoidInternalStateMvasVent","solenoidCurrentMvasVent"),
    ("solenoidInternalStateMvas","solenoidCurrentMvas"),
    ("solenoidInternalStateLoxFill","solenoidCurrentLoxFill"),
    ("solenoidInternalStateLoxVent","solenoidCurrentLoxVent"),
    ("solenoidInternalStateLngFill","solenoidCurrentLngFill"),
    ("solenoidInternalStateLngVent","solenoidCurrentLngVent"),
]